openapi: 3.0.0
info:
  title: Library Management API
  version: 1.0.0

paths:
  /books:
    get:
      summary: Liste tous les livres
      operationId: getBooks
      tags:
        - Books
      responses:
        '200':
          description: Liste des livres
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/{id}:
    get:
      summary: Récupère un livre par son ID
      operationId: getBookById
      tags:
        - Books
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Livre trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Requête invalide
        '404':
          description: Livre non trouvé
        '500':
          description: Erreur serveur

  /books/add:
    post:
      summary: Ajoute un nouveau livre
      operationId: addBook
      tags:
        - Books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRequest'
      responses:
        '201':
          description: Livre créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Requête invalide
        '500':
          description: Erreur serveur

  /books/delete:
    delete:
      summary: Supprime un livre
      operationId: deleteBook
      tags:
        - Books
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: ID du livre à supprimer
      responses:
        '200':
          description: Livre supprimé
        '500':
          description: Erreur serveur

  /books/copy:
    get:
      summary: Récupère la liste des copies d'un livre
      operationId: getAllBookCopy
      tags:
        - BookCopies
      responses:
        '200':
          description: Copie du livre trouvée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /books/copy/{id}:
    get:
      summary: récupère une copie d'un livre par son id
      operationId: getBookCopyById
      tags:
        - BookCopies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Copie du livre trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCopy'
        '400':
          description: Requête invalide
        '404':
          description: Copie du livre non trouvée
        '500':
          description: Erreur serveur
    delete:
      summary: Supprime une copie d'un livre
      operationId: deleteBookCopy
      tags:
        - BookCopies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID de la copie du livre à supprimer
      responses:
        '200':
          description: Copie du livre supprimée
        '500':
          description: Erreur serveur

  /books/copy/add:
    post:
      summary: Ajoute une copie d'un livre
      operationId: addBookCopy
      tags:
        - BookCopies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCopyRequest'
      responses:
        '201':
          description: Copie du livre créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookCopy'
        '400':
          description: Requête invalide
        '500':
          description: Erreur serveur
      
  /books/format:
    get:
      summary: récupère la liste de format d'un livre
      operationId: getAllBookFormat
      tags:
        - BookFormats
      responses:
        '200':
          description: Format du livre trouvée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookFormat'

  /books/format/{id}:
    get:
      summary: récupère un format d'un livre par son id
      operationId: getBookFormatById
      tags:
        - BookFormats
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Format du livre trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookFormat'
        '400':
          description: Requête invalide
        '404':
          description: Format du livre non trouvé
        '500':
          description: Erreur serveur
    put:
      summary: Met à jour un format d'un livre
      operationId: updateBookFormat
      tags:
        - BookFormats
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookFormat'
      responses:
        '200':
          description: Format du livre mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookFormat'
        '400':
          description: Requête invalide
        '404':
          description: Format du livre non trouvé
        '500':
          description: Erreur serveur
    delete:
      summary: Supprime un format d'un livre
      operationId: deleteBookFormat
      tags:
        - BookFormats
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            description: ID du format du livre à supprimer
      responses:
        '200':
          description: Format du livre supprimée
        '500':
          description: Erreur serveur

  /stockMovements:
    get:
      summary: récupère la liste des mouvements de stock
      operationId: getAllStockMovements
      tags:
        - StockMovements
      responses:
        '200':
          description: Mouvements de stock trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockMovement'

  /stockMovements/{id}:
    get:
      summary: récupère un mouvement de stock par son id
      operationId: getStockMovementById
      tags:
        - StockMovements
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mouvement de stock trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockMovement'
        '400':
          description: Requête invalide
        '404':
          description: Mouvement de stock non trouvé
        '500':
          description: Erreur serveur

  /stockMovements/add:
    post:
      summary: Ajoute un mouvement de stock
      operationId: addStockMovement
      tags:
        - StockMovements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockMovementRequest'
      responses:
        '201':
          description: Mouvement de stock créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockMovement'
        '400':
          description: Requête invalide
        '500':
          description: Erreur serveur

  /stockMovements/delete/{id}:
    delete:
      summary: Supprimer un livre spécifique
      operationId: deleteStockMovementById
      tags:
        - StockMovements
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Mouvement de stock supprimé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockMovement'
        '400':
          description: Requête invalide
        '404':
          description: Mouvement de stock non trouvé
        '500':
          description: Erreur serveur

  /stock/book/{id}:
    get:
      summary: Récupère la quantité en stock d'un livre.
      operationId: getStockQuantityOfBookById
      tags: 
        - StockMovements
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: nombres des stocks d'une livre spécifique trouvéQuantité en stock du livre récupérée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockQuantityDTO'
        '400':
          description: Requête invalide
        '404':
          description: Stock du livre non trouvé
        '500':
          description: Erreur serveur
      



components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          format: uuid
        isbn:
          type: string
        title:
          type: string
        publishDate:
          type: string
          format: date
        description:
          type: string
        urlImage:
          type: string
        genre:
          $ref: '#/components/schemas/GenreEnum'
        createDatetime:
          type: string
          format: date-time
        author:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        bookFormat:
          type: array
          items:
            $ref: '#/components/schemas/BookFormat'
        library:
          $ref: '#/components/schemas/Library'

    BookRequest:
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string
        publishDate:
          type: string
          format: date
        description:
          type: string
        urlImage:
          type: string
        genre:
          $ref: '#/components/schemas/GenreEnum'
        author:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        bookFormat:
          type: array
          items:
            $ref: '#/components/schemas/BookFormat'
        library:
          $ref: '#/components/schemas/Library'

    GenreEnum:
      type: string
      enum:
        - ROMAN
        - SCIENCE_FICTION
        - FANTASY
        - POLICIER
        - THRILLER
        - HORREUR
        - AVENTURE
        - BIOGRAPHIE
        - HISTOIRE
        - POESIE
        - THEATRE
        - JEUNESSE
        - BANDE_DESSINEE
        - MANGA
        - DEVELOPPEMENT_PERSONNEL
        - RELIGION
        - PHILOSOPHIE
        - SCIENCES
        - INFORMATIQUE
        - ECONOMIE
        - POLITIQUE
        - ART
        - CUISINE
        - VOYAGE
        - SANTE

    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    BookFormat:
      type: object
      properties:
        id:
          type: string
          format: uuid
        format:
          type: string
          enum:
          - SMALL
          - MEDIUM
          - LARGE

    Library:
      type: object
      properties:
        id:
          type: string
          format: uuid

    BookCopy:
      type: object
      properties:
        id:
          type: string
          format: uuid
        bookFormat:
          $ref: '#/components/schemas/BookFormat'
        priceBook:
          type: array
          items:
            $ref: '#/components/schemas/PriceBook'

    BookCopyRequest:
      type: object
      properties:
        bookFormat:
          $ref: '#/components/schemas/BookFormat'
        priceBook:
          type: array
          items:
            $ref: '#/components/schemas/PriceBook'
    
    PriceBook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        price:
          type: number
          format: float
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    StockMovement:
      type: object
      properties:
        id:
          type: string
          format: uuid
        bookCopy:
          $ref: '#/components/schemas/BookCopy'
        quantity:
          type: integer
        movementTypeEnum:
          type: string
          enum:
            - IN
            - OUT
        createDatetime:
          type: string
          format: date-time

    StockMovementRequest:
      type: object
      properties:
        bookCopy:
          $ref: '#/components/schemas/BookCopy'
        quantity:
          type: integer
        reason:
          type: string
        movementTypeEnum:
          type: string
          enum:
            - IN
            - OUT

    StockQuantityDTO:
      type: object
      properties:
        quantity:
          type: integer
        bookTitle:
          type: string
        bookFormat:
          type: string